name: Docker Image CI

on:
  # Schedule updates (each monday)
  schedule: [ { cron: "0 0 * * 1" } ]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crossoverjie/starrocks-docker-dev:latest
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{  secrets.DOCKER_USERNAME  }}
        # Password or personal access token used to log against the Docker registry
        password: ${{  secrets.DOCKER_PASSWORD  }}
    - name: Push
      run: docker push crossoverjie/starrocks-docker-dev:latest
